-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE IF NOT EXISTS chat.user
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL,
    nickname      TEXT,
    chat_id       BIGINT,
    state         TEXT
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS chat.user;
DROP SCHEMA IF EXISTS chat;
-- +goose StatementEnd
