services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_tofl
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Artem557
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "8082:9090"
    volumes:
      - "./metrics/prometheus:/etc/prometheus"
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "8083:9100"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      #- "./metrics/grafana/grafana.ini:/etc/grafana/grafana.ini"
    env_file:
      - .env
    depends_on:
      - prometheus

volumes:
  grafana_data:
  db-data:
  mongo_data:
