CREATE SCHEMA IF NOT EXISTS global;

CREATE TABLE IF NOT EXISTS global.user
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_at TIMESTAMPTZ NOT NULL,
    last_action   TIMESTAMPTZ NOT NULL,
    nickname      TEXT,
    chat_id       BIGINT,
    state         TEXT
);